---
production:
  credentials:
  secure_credentials: true
  ca_path:
  gocdb_base_url:
  appdb_base_url:
  debug: false

development:
  credentials:
  secure_credentials: true
  ca_path:
  gocdb_base_url:
  appdb_base_url:
  debug: true

test:
  credentials:
  secure_credentials: true
  ca_path:
  gocdb_base_url:
  appdb_base_url:
  debug: true
