---
production:
  format: table
  credentials: "<%= ENV['HOME'] %>/.globus/usercred.pem"
  ca_path: '/etc/grid-security/certificates'
  gocdb_base_url: 'https://goc.egi.eu'
  appdb_base_url: 'https://appdb-pi.egi.eu'
  debug: false

development:
  format: table
  credentials: "<%= ENV['HOME'] %>/.globus/usercred.pem"
  ca_path: '/etc/grid-security/certificates'
  gocdb_base_url: 'https://goc.egi.eu'
  appdb_base_url: 'https://appdb-pi.egi.eu'
  debug: true

test:
  format: table
  credentials: "<%= ENV['HOME'] %>/.globus/testcred.pem"
  ca_path: '/etc/grid-security/certificates'
  gocdb_base_url: 'http://localhost/goc'
  appdb_base_url: 'http://localhost/appdb-pi'
  debug: true
